### ISSUE TITLE
A quick question.

### ISSUE THREAD

**Issue by Rover656** [Android4Lumia/bootloader_msm8227#2]
Hi there,
I have been looking around the targets folder and found a folder for the Qualcomm Snapdragon 400 MSM8226. Would this mean that it is compatible with the nokia Lumia 640 and such devices, or is the code incomplete. I am asking because I am interested in modifying my 640.
I am sorry if this is a stupid question, I am aware you stating it isn't compatible on the xda thread.
Thank you if you reply!

**Comment by Rover656** [comment]
Oops, did more research, I am wrong.

**Comment by feherneoh** [comment]
We could actually build for the 640, but we could not flash or boot it on that phone, as there is no bootloader unlock available for that phone yet

**Comment by Rover656** [comment]
Yep, i found that out after lots more research, thanks anyways!

**Comment by jhay06** [comment]
> We could actually build for the 640, but we could not flash or boot it on that phone, as there is no bootloader unlock available for that phone yet
i managed to ublock the bootloader , whats next?
