### ISSUE TITLE
Quick Rundown

### ISSUE THREAD

**Issue by 0x0000ff** [Android4Lumia/bootloader_msm8227#3]
Apologies if this isn't the right place to enquire.

I'd just like to know how you have managed to run a custom boot-oader on these devices, assuming that Qualcom's boot process is the same as that on their android counterparts.

I've been looking for a way to unlock the bootloader on my Galaxy S5, and have come up short (there is a way to change the CID on the internal storage so that the phone thinks it's a 'developer edition' device, but mine is incompatible.

**Comment by feherneoh** [comment]
The vulnerability used to unlock these devices isn't applicable for the SoC of Galaxy S5, but is supposed to work on any device with an MSM8960/MSM8x30/MSM8x27/APQ8064 SoC

**Comment by 0x0000ff** [comment]
Thanks for your input. I kinda thought it would be a hail-mary last ditch effort.
