### ISSUE TITLE
Lumia 640 (dempsey)

### ISSUE THREAD

**Issue by jhay06** [Android4Lumia/bootloader_msm8227#5]
I managed to unlock the bootloader but theres no bootloader_msm available ,  i know its too old but hop[ing someone can build

**Comment by feherneoh** [comment]
1. The bootloader unlock available for Lumia 640 doesn't allow you to replace the bootloader
2. That phone obviously has a different SoC than what this repo is for
3. There are people working on these newer Lumias, but none of them are even remutely usable yet, and barely any of them can even boot
